let sugerimente=[
    'lapte',
    'pâine ',
    'pâine integrală',
    'ouă',
    'faină',
    'cereale',
    'apă carbocazoasă',
    'pastă de dinți',
    'paste',
    'mere',
    'pere',
    'banane',
    'pepene verde',
    'pepene galben',
    'roșii',
    'zahăr',
    'zahăr brun',
    'Fairy',
    'Lenor',
    'Nivea Men',
    'Nivea',
    'Dove',
    'cașcaval',
    'smântănă',
    'deodorant',
    'bere',
    'pateu de porc',
    'cartofi',
]
